# Generated by Django 5.1.1 on 2024-09-25 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_speciality'),
        ('teacher', '0002_remove_teacher_level_alter_teacher_speciality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='speciality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='teacher.speciality'),
            preserve_default=False,
        ),
    ]
