# Generated by Django 5.1.1 on 2024-09-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='level',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='speciality',
            field=models.ManyToManyField(to='teacher.speciality'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='level',
            field=models.ManyToManyField(to='course.level'),
        ),
    ]
