# Generated by Django 5.1.1 on 2024-10-14 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('section', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='section.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.student')),
                ('teacher_course_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.teachercourseassignment')),
            ],
            options={
                'db_table': 'course_registration',
                'unique_together': {('student', 'teacher_course_assignment')},
            },
        ),
    ]
