# Generated by Django 5.1.1 on 2024-09-24 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('section', '0001_initial'),
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('create_date', models.TimeField(auto_now_add=True)),
                ('update_date', models.TimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.course')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.level')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='section.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teacher.teacher')),
            ],
            options={
                'db_table': 'course_registration',
            },
        ),
    ]
