# Generated by Django 5.1.1 on 2024-09-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('registration', '0001_initial'),
        ('teacher', '0002_remove_teacher_level_alter_teacher_speciality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseregistration',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseregistration',
            name='teacher',
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='course',
            field=models.ManyToManyField(to='course.course'),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='teacher',
            field=models.ManyToManyField(to='teacher.teacher'),
        ),
    ]
