# Generated by Django 5.1.1 on 2024-10-14 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistration',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='grade.grade'),
            preserve_default=False,
        ),
    ]
