# Generated by Django 5.1.1 on 2024-10-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('registration', '0002_courseregistration_grade'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseregistration',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='courseregistration',
            name='teacher_course_assignment',
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='teacher_course_assignment',
            field=models.ManyToManyField(to='course.teachercourseassignment'),
        ),
    ]
