# Generated by Django 5.1.1 on 2024-09-25 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='registration_status',
        ),
    ]
